In [1]:
import os
import pandas as pd
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import math

In [12]:
data_file = "dataset.csv"
df = pd.read_csv(data_file, encoding='ISO-8859-1')


In [13]:
df.head()

EMP.ID  Oxgyen saturation  Heart Rate (bpm)  Glucose (mg/dL)  \
0       1                 95                60               47   
1       2                 95                81               48   
2       3                 97                64               66   
3       4                 96                93               55   
4       5                 95                70               51   

   CORONARY HEART DISEASE  (mg/dL)  Asthma Body Temperature (°C)  Label  
0                              103      93                37.1°C      0  
1                              124      95                37.2°C      0  
2                              122      99                36.9°C      0  
3                              107      84                37.1°C      0  
4                              124      97                36.8°C      0

In [5]:
df

EMP.ID  Oxgyen saturation  Heart Rate (bpm)  Glucose (mg/dL)  \
0          1                 95                60               47   
1          2                 95                81               48   
2          3                 97                64               66   
3          4                 96                93               55   
4          5                 95                70               51   
...      ...                ...               ...              ...   
3739    3740                 80               146              207   
3740    3741                 52               153              391   
3741    3742                 85               140              217   
3742    3743                 89               164              383   
3743    3744                 72               161              293   

      CORONARY HEART DISEASE  (mg/dL)  Asthma Body Temperature (°C)  Label  
0                                 103      93                37.1°C      0  
1                                 124      95                37.2°C      0  
2                                 122      99                36.9°C      0  
3                                 107      84                37.1°C      0  
4                                 124      97                36.8°C      0  
...                               ...     ...                   ...    ...  
3739                               45      41                40.2°C      1  
3740                               48      47                39.5°C      1  
3741                               68      43                40.5°C      1  
3742                               51      40                39.1°C      1  
3743                               27      52                39.8°C      1  

[3744 rows x 8 columns]

In [14]:
df = df.drop(['Label'],axis=1)

In [7]:
df

EMP.ID  Oxgyen saturation  Heart Rate (bpm)  Glucose (mg/dL)  \
0          1                 95                60               47   
1          2                 95                81               48   
2          3                 97                64               66   
3          4                 96                93               55   
4          5                 95                70               51   
...      ...                ...               ...              ...   
3739    3740                 80               146              207   
3740    3741                 52               153              391   
3741    3742                 85               140              217   
3742    3743                 89               164              383   
3743    3744                 72               161              293   

      CORONARY HEART DISEASE  (mg/dL)  Asthma Body Temperature (°C)  
0                                 103      93                37.1°C  
1                                 124      95                37.2°C  
2                                 122      99                36.9°C  
3                                 107      84                37.1°C  
4                                 124      97                36.8°C  
...                               ...     ...                   ...  
3739                               45      41                40.2°C  
3740                               48      47                39.5°C  
3741                               68      43                40.5°C  
3742                               51      40                39.1°C  
3743                               27      52                39.8°C  

[3744 rows x 7 columns]

In [15]:
X = df
X.replace('?', 0)
print(X.columns)
X = np.array(X)
X

Index(['EMP.ID', 'Oxgyen saturation', 'Heart Rate (bpm)', 'Glucose (mg/dL)',
       'CORONARY HEART DISEASE  (mg/dL)', 'Asthma', 'Body Temperature (°C)'],
      dtype='object')


array([[1, 95, 60, ..., 103, 93, '37.1°C'],
       [2, 95, 81, ..., 124, 95, '37.2°C'],
       [3, 97, 64, ..., 122, 99, '36.9°C'],
       ...,
       [3742, 85, 140, ..., 68, 43, '40.5°C'],
       [3743, 89, 164, ..., 51, 40, '39.1°C'],
       [3744, 72, 161, ..., 27, 52, '39.8°C']], dtype=object)

In [16]:
def create_data(x, look_back=1):
    dataX, datay = [], []
    for i in range(3000):
        a = X[i:i + look_back,1]
        dataX.append(a)
        datay.append(X[i + look_back,1])
    return np.array(dataX), np.array(datay)


In [17]:
X, Y = create_data(X, look_back=100 )

In [18]:
print(X)

[[95 95 97 ... 98 97 95]
 [95 97 96 ... 97 95 96]
 [97 96 95 ... 95 96 98]
 ...
 [33 28 20 ... 77 51 72]
 [28 20 53 ... 51 72 38]
 [20 53 26 ... 72 38 85]]


In [30]:
print(Y)

[96 98 97 ... 38 85 83]


In [31]:
X = np.reshape(X, (X.shape[0], X.shape[1]))
#Xout = np.reshape(X, ( 1, X.shape[0]))
print(X.shape)

(3000, 100)


In [32]:
from sklearn import svm


In [33]:
#from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [35]:
clf=svm.SVR()

clf.fit(x_train,y_train)

test=clf.predict(x_test)
#print(test)
y_test = [int(float(x)) for x in y_test]
print(y_test)
pred = [int(x) for x in test]
print(pred)

[81, 45, 78, 35, 97, 28, 96, 49, 98, 96, 48, 97, 81, 97, 34, 98, 35, 95, 81, 68, 23, 98, 95, 41, 77, 41, 88, 73, 95, 56, 42, 97, 40, 98, 47, 97, 97, 98, 97, 20, 95, 98, 53, 96, 34, 52, 39, 97, 69, 98, 98, 84, 40, 96, 53, 95, 96, 63, 96, 95, 96, 29, 40, 72, 97, 83, 95, 95, 97, 95, 98, 95, 97, 97, 96, 96, 70, 95, 38, 62, 66, 96, 95, 68, 40, 47, 95, 98, 97, 97, 98, 95, 97, 83, 96, 98, 61, 95, 87, 84, 96, 96, 84, 95, 95, 62, 95, 95, 97, 95, 30, 98, 20, 95, 49, 53, 98, 69, 64, 24, 97, 97, 24, 98, 97, 95, 95, 98, 84, 23, 97, 95, 97, 97, 96, 34, 62, 97, 96, 98, 95, 96, 54, 22, 26, 96, 30, 98, 74, 98, 20, 98, 98, 84, 97, 62, 95, 98, 32, 40, 96, 98, 95, 50, 95, 59, 95, 98, 96, 96, 57, 96, 32, 23, 96, 22, 98, 98, 98, 26, 65, 96, 97, 75, 96, 73, 77, 69, 30, 95, 97, 77, 20, 97, 45, 95, 39, 88, 95, 98, 97, 96, 98, 98, 54, 97, 72, 97, 21, 98, 98, 96, 98, 72, 82, 97, 67, 56, 98, 98, 86, 80, 43, 98, 95, 82, 71, 96, 97, 97, 98, 96, 96, 97, 97, 43, 59, 98, 24, 98, 96, 98, 98, 49, 97, 98, 98, 97, 98, 98,

In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 81,  0,  0],
       [ 0,  0,  0, ..., 89,  0,  0],
       [ 0,  0,  0, ..., 96,  0,  0]], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred)
print(100-accuracy)

99.84833333333333
